services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-dev
    ports:
      - "3000:3000"
    volumes:
      - ./local-dev/config:/app/config
    restart: unless-stopped
